server:
  port: 8081
application:
  fhir:
    server-url: http://localhost:8080/fhir/hapi
    version: R4
    input: /home/owt-hau/work/tmp?fileName=hl7v2.patient
camel:
  component:
    servlet:
      mapping:
        context-path: /camel/*
  dataformat:
    jackson:
      auto-discover-object-mapper: true
spring:
  activemq:
    broker-url: tcp://localhost:61616
    username: admin
    password: admin